name: Build

on: push

jobs:
  server:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.tools.wmflabs.org/toolforge-php72-sssd-web
      env:
        COMPOSER_ALLOW_SUPERUSER: 1
    steps:
      - uses: actions/checkout@v1
      - run: 'composer install'
        working-directory: server
      - run: 'composer test'
        working-directory: server
  client:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.tools.wmflabs.org/toolforge-node10-sssd-web
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v1
      - run: npm ci --verbose --unsafe-perm
      - run: npm run build --if-present
      - run: npm test
