name: Build

on: push

jobs:
  server:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.tools.wmflabs.org/toollabs-php72-web
      env:
        COMPOSER_ALLOW_SUPERUSER: 1
    steps:
      - uses: actions/checkout@v1
      - run: 'composer install'
        working-directory: server
      - run: 'composer test'
        working-directory: server
  client:
    runs-on: ubuntu-latest
    container:
      image: 'docker-registry.tools.wmflabs.org/toollabs-node10-web'
    steps:
      - uses: actions/checkout@v1
      - run: 'npm install --verbose --unsafe-perm'
        working-directory: client
      - run: 'npm test'
        working-directory: client
