name: Client

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 'docker-registry.tools.wmflabs.org/toollabs-node10-web'
    steps:
      -
        working-directory: /github/workflow
        run: 'ls -la'
