name: Client

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 'docker-registry.tools.wmflabs.org/toollabs-node10-web'
    steps:
      -
        run: 'ls -la /__w'
      -
        run: 'ls -la /__e'
      -
        run: 'ls -la /__t'
      -
        run: 'ls -la /github/home'
      -
        run: 'ls -la /github/workflow'
