name: Server

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.tools.wmflabs.org/toollabs-php72-web
      env:
        COMPOSER_ALLOW_SUPERUSER: 1
    steps:
      -
        uses: actions/checkout@v1
      - 
        working-directory: server
        run: 'composer install'
      -
        working-directory: server
        run: 'composer test'
